services:
  frontend:
    image: node:20-alpine
    command: npm run dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTPS
    volumes:
      - ./backend:/app
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql://user:password@database:5432/app?serverVersion=16&charset=utf8
      - SERVER_NAME=:80
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    volumes:
      - how_does_it_ends_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  how_does_it_ends_data: 